# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2
build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  commands:
    - python -m pip install uv
    - uvx hatch run docs:build
    - mv docs/_build $READTHEDOCS_OUTPUT
